service: users-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  httpApi:
    cors: true
  environment:
    DB_URL: ${env:DB_URL, ''}
    QUEUE_URL:
      Ref: UsersQueue
    SENDER_EMAIL: ${env:SENDER_EMAIL, ''}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            Fn::GetAtt:
              - UsersQueue
              - Arn
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource: "*"

functions:
  getUsers:
    handler: handler.getUsers
    events:
      - httpApi:
          path: /users
          method: GET

  getUser:
    handler: handler.getUser
    events:
      - httpApi:
          path: /users/{id}
          method: GET

  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /users
          method: POST

  updateUser:
    handler: handler.updateUser
    events:
      - httpApi:
          path: /users/{id}
          method: PUT

  deleteUser:
    handler: handler.deleteUser
    events:
      - httpApi:
          path: /users/{id}
          method: DELETE

  # Worker Lambda — triggered by SQS, simulates sending emails
  worker:
    handler: handler.worker
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - UsersQueue
              - Arn

resources:
  Resources:
    UsersQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: users-events-queue
