service: users-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2

functions:
  getUsers:
    handler: handler.getUsers
    events:
      - http:
          path: users
          method: get        
  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete             