service: users-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  httpApi:
    cors: true   

functions:
  getUsers:
    handler: handler.getUsers
    events:
      - httpApi:   
          path: /users
          method: GET

  deleteUser:
    handler: handler.deleteUser
    events:
      - httpApi:   
          path: /users/{id}
          method: DELETE